### ISSUE TITLE
初始化数据库SQL文件，非最新完整数据，无法正常使用！

### ISSUE THREAD

**Issue by Peezz** [xiya-team/go-cms#61]
问题: data 目录下，go-cms/data/database.sql 非最新完整数据结构和初始化数据，无法正常登录后续操作！请问一下，能否把该SQL文件更新到最新呢？
![image](https://user-images.githubusercontent.com/7435945/78814648-8e596280-7a01-11ea-9c70-11f0091751c0.png)

**Comment by hwsyy** [comment]
是的

**Comment by Zz1204** [comment]
> 是的

请问一下，最新的sql文件可以从哪里下载

**Comment by qq247912981** [comment]
给个admin的初始化脚本赛

**Comment by o624366705** [comment]
数据！数据！数据！

**Comment by qialie** [comment]
入群

**Comment by qialie** [comment]
入群

**Comment by lemonc2009** [comment]
群也进不了了，作者微信禁止从二维码加了。
